//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHomework2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Menu
    {
        public Menu()
        {
            this.Roles = new HashSet<Role>();
        }

        [DisplayName("Menu No.")]
        public string MenuNo { get; set; }

        [DisplayName("Link Type")]
        public Nullable<byte> LinkType { get; set; }

        [DisplayName("Title")]
        public string LinkName { get; set; }

        [DisplayName("Link URL")]
        public string LinkURL { get; set; }

        public Nullable<byte> Status { get; set; }

        [DisplayName("Level")]
        public Nullable<byte> MenuLevel { get; set; }
        public Nullable<System.DateTime> CeateDate { get; set; }
        public Nullable<int> Createuser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUser { get; set; }

        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<Role> Roles { get; set; }

        public List<Menu> ListA { get; set; }
        public List<Menu> ListC { get; set; }
        public LoginInfo sideNav { get; set; }
    }
}
