//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHomework2.Models
{
    using System;
    using System.Collections.Generic;

    public partial class User
    {
        public User()
        {
            this.LoginInfoes = new HashSet<LoginInfo>();
            this.Menus = new HashSet<Menu>();
            this.Menus1 = new HashSet<Menu>();
            this.Roles = new HashSet<Role>();
            this.Roles1 = new HashSet<Role>();
            this.User1 = new HashSet<User>();
            this.User11 = new HashSet<User>();
        }

        public int UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUser { get; set; }

        public virtual ICollection<LoginInfo> LoginInfoes { get; set; }
        public virtual ICollection<Menu> Menus { get; set; }
        public virtual ICollection<Menu> Menus1 { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<Role> Roles1 { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<User> User11 { get; set; }
        public virtual User User3 { get; set; }

        public List<Role> ListA { get; set; }
        public List<User> ListB { get; set; }
        public LoginInfo sideNav { get; set; }

        public string ModifyMessage { get; set; }
    }
}
